// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJoztBW9407KfBK8vUAAAbgLRgLSkRTvw',
    appId: '1:835265314175:web:203bc3369594778b96ae4a',
    messagingSenderId: '835265314175',
    projectId: 'sublimer-c3243',
    authDomain: 'sublimer-c3243.firebaseapp.com',
    storageBucket: 'sublimer-c3243.firebasestorage.app',
    measurementId: 'G-630BTVW6E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7RlIjOvm7tRwfrwMNQsFLaOJzMKVkG6o',
    appId: '1:835265314175:android:0423b340a584c59496ae4a',
    messagingSenderId: '835265314175',
    projectId: 'sublimer-c3243',
    storageBucket: 'sublimer-c3243.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTTlkhYa8Nnr2WLuKDS-O9i4JhiIMom-w',
    appId: '1:835265314175:ios:0e75c8cf4244aebe96ae4a',
    messagingSenderId: '835265314175',
    projectId: 'sublimer-c3243',
    storageBucket: 'sublimer-c3243.firebasestorage.app',
    iosClientId: '835265314175-lc6iaripglqmgislacvad7hr6kf5hvsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.applicationSublimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTTlkhYa8Nnr2WLuKDS-O9i4JhiIMom-w',
    appId: '1:835265314175:ios:0e75c8cf4244aebe96ae4a',
    messagingSenderId: '835265314175',
    projectId: 'sublimer-c3243',
    storageBucket: 'sublimer-c3243.firebasestorage.app',
    iosClientId: '835265314175-lc6iaripglqmgislacvad7hr6kf5hvsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.applicationSublimer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJoztBW9407KfBK8vUAAAbgLRgLSkRTvw',
    appId: '1:835265314175:web:984347dfe1d6d75696ae4a',
    messagingSenderId: '835265314175',
    projectId: 'sublimer-c3243',
    authDomain: 'sublimer-c3243.firebaseapp.com',
    storageBucket: 'sublimer-c3243.firebasestorage.app',
    measurementId: 'G-SCEGNZMEEC',
  );
}
